version: "3.1"

services:
  # mongo:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - 27018:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: root
  #   networks:
  #     - SyndicatApplication
  #   volumes:
  #     - ./db-data/:/data/db

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: root
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #   networks:
  #     - SyndicatApplication

networks:
  SyndicatApplication:
    driver: bridge

  # Codespaces secrets  "root" github
